### ISSUE TITLE
Use `NSViewController.present()` with custom animator

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#108]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/gifski-app/issues/108)

Currently, we do this: https://github.com/sindresorhus/Gifski/blob/56511ac4c7deb68b2e39490e0bef45180634b128/Gifski/util.swift#L2436-L2455

The benefit of using `present` is that it's possible to dismiss the view controller to go back to the previous one. For example, when the user cancels the editing, we could just dismiss that view controller.

https://developer.apple.com/documentation/appkit/nsviewcontroller/1434431-present
https://stackoverflow.com/questions/28454291/transitioning-between-view-controller-os-x/28493373#28493373

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Submitted pull Requests
- [#139 Use custom presentation animator](https://issuehunt.io/r/sindresorhus/gifski-app/pull/139)
- [#241 Use NSViewController.present() with custom animator #108](https://issuehunt.io/r/sindresorhus/gifski-app/pull/241)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the feedback given in https://github.com/sindresorhus/Gifski/pull/139.

**Comment by hazeycode** [comment]
PR #241

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/Gifski/pull/241#issuecomment-869121738

**Comment by sindresorhus** [comment]
@hazeycode I wanted to give you the bounty for your effort, but the IssueHunt website is broken and I cannot access the issue page there... Same issue as: https://spectrum.chat/issuehunt/general/error-when-accessing-an-issue-page~edd3be59-9228-472f-ae32-ce888e56bc1c

**Comment by hazeycode** [comment]
@sindresorhus thanks for awarding the bounty! :)
