### ISSUE TITLE
Tabbing is broken in the edit view

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#109]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/gifski-app/issues/109)

The Dimensions dropdown has the first focus, if you tab you get Width, then Height, then the trimmer view. Instead of the trimmer view, it should have been the "pixels/percentage" dropdown.

When the edit view is presented, if you press Shift+Tab, it moves to focus to the trimmer view, if you press Esc then, the trimmer is hidden. We should find a way to prevent the trimmer from disappearing.

I was also thinking, maybe we should make the trimmer view the initial first responder instead of the "Dimensions" dropdown. You would then be able to press Space to view the video, which is nicer, I think. We could make it so that when you tab once, the dimension dropdown is focused.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)
### Submitted pull Requests
- [#132 Tabbing is broken in the edit view #109](https://issuehunt.io/r/sindresorhus/gifski-app/pull/132)
- [#141 Fix Edit window tabbing](https://issuehunt.io/r/sindresorhus/gifski-app/pull/141)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by NehaKushwah993** [comment]
Hi, I think I can fix this issue. But first I don't know how can I create pull request because I am not able to create any sub_branch or branch. Please let me know that process so I will start my process for other issues as well.

**Comment by NehaKushwah993** [comment]
Hi, I have fixed this issue :

-  Instead of the trimmer view, it should have been the "pixels/percentage" dropdown.
-  we should make the trimmer view the initial first responder instead of the "Dimensions" dropdown.
- if you press Shift+Tab, it moves to focus to the trimmer view, if you press Esc then, the trimmer is hidden.

These 3 issues are fixed, please take a look in my pullRequest.

-Neha

**Comment by NehaKushwah993** [comment]
Hi, did you look in to this?

**Comment by NehaKushwah993** [comment]
Hey, should I send you it's video?
