### ISSUE TITLE
Add support for frame diffing

### ISSUE THREAD

**Issue by fnky** [sindresorhus/Gifski#110]
It would be nice to support something like [`anim_encoder`](https://github.com/sublimehq/anim_encoder) for simpler gifs. This can help tremendously with decreasing the size of a gif, where only individual areas change, and other areas stay the same.

Jon Skinner, the creator of anim_encoder, has an [excellent post about how he created his encoder](https://www.sublimetext.com/~jps/animated_gifs_the_hard_way.html).

**Comment by fnky** [comment]
Anim encoder doesn't acutally output a gif, but individual PNGs and a JSON/JS file with timecodes to drive the animation with JavaScript. So not applicable to Gifski.

**Comment by kornelski** [comment]
GIF already has delta frames.
