### ISSUE TITLE
Various suggestions

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/Gifski#111]
👋 I just tried the app and it looks pretty promising so I wanted to provide some feedback:

- It might be cool if there was a startup animation where the colored stripes kind of entered the window.
- The colored stripes look a bit off on a vibrant background, perhaps they should be vibrant/slightly transparent too.
- Clicking somewhere in the initial window should open up the "Open..." dialog, perhaps a button or an icon could be added, or maybe just clicking anywhere in the window should open up the dialog.
- When dragging the FPS slider it may happen that the reported FPS are the same, while the estimated size changes, so I guess that slider is actually using fractional FPS? I think either fractional FPS should be shown in the interface or the slider should have fixed 1fps intervals.
- File size estimates are way off, I got a ~3mb file over a ~90mb estimate https://github.com/sindresorhus/Gifski/issues/41.
- The remaining time estimate is a bit off. Looking at the progress circle it looks like the remaining time should be pretty predictable as it seems like each percentage point takes roughly a constant amount of time to process. I think perhaps the time estimate should be recalculated after each percentage point with the following formula: `( ( 100 / number_of_percentage_points_so_far ) - 1 ) * time_elapsed_so_far`.
- It's possible to go back from the trimming window by clicking the "Cancel" button, but:
  - clicking the cancel button on the conversion window doesn't go back to the trimming window (maybe I changed my mind last-second or with the chosen settings the thing takes forever to process or something).
  - there's no button for going back from the result window (maybe once looking at the resulting GIF one figures the settings can be tuned better).
- Maybe some values used in the trimming window, like FPS and quality, should be remembered across conversions.
- The black background in the trimming window behind my actual video to trim feels weird to me, it makes it difficult to understand where the actual edges of my video are, especially if I'm recording something very dark like a terminal session. I think there shouldn't be any background color/image behind my video, but if for some reason there must be one probably a [transparency pattern](https://as1.ftcdn.net/jpg/01/05/30/40/500_F_105304079_nhUpNJwmbxxkqZDyeX4LukvBBxGTX70A.jpg) should be used instead.
- It would be interesting to add the ability to precisely crop the video, as if one is recording a particular window using Mojave's built-in area recording feature it will be difficult to precisely select the correct area.
- It might be useful to mention a few recommended screen-recording apps in the readme. For instance Mojave's built-in features don't currently allow to easily record only a particular window, a recommended third-party app than can do that would be useful to me for instance.

Hope that's useful, thanks for making the app!

**Comment by sindresorhus** [comment]
Thanks for all the great feedback 🙌

> It might be cool if there was a startup animation where the colored stripes kind of entered the window.

Already planned, but I'm waiting until I can use SwiftUI as doing advanced animations with AppKit is annoying. This is tracked in https://github.com/sindresorhus/Gifski/issues/104.

> The colored stripes look a bit off on a vibrant background, perhaps they should be vibrant/slightly transparent too.

I've tried reducing the opacity, but even with 0.7, it doesn't make a difference, and with 0.5 and lower, it looks too washed out.

> Clicking somewhere in the initial window should open up the "Open..." dialog, perhaps a button or an icon could be added, or maybe just clicking anywhere in the window should open up the dialog.

There's already a "Open..." menu item and a Command+O shortcut. And you can drag and drop. Not sure this is actually needed. You're the first one to request this. Are there any other Mac apps that has drag and drop that makes it clickable to "open"?

> When dragging the FPS slider it may happen that the reported FPS are the same, while the estimated size changes, so I guess that slider is actually using fractional FPS? I think either fractional FPS should be shown in the interface or the slider should have fixed 1fps intervals.

Yeah, we should normalize the numbers from that slider to the closest whole FPS.

> File size estimates are way off, I got a ~3mb file over a ~90mb estimate #41.

Yeah... It's not easy to fix. Help welcome!

> The remaining time estimate is a bit off.

I haven't noticed that, but we'll look into it.

> clicking the cancel button on the conversion window doesn't go back to the trimming window (maybe I changed my mind last-second or with the chosen settings the thing takes forever to process or something).

Good point! That would be a better behavior.

> there's no button for going back from the result window (maybe once looking at the resulting GIF one figures the settings can be tuned better).

Agreed, we should add a back button.

> Maybe some values used in the trimming window, like FPS and quality, should be remembered across conversions.

We persist the quality, but not sure it makes sense to persist the FPS. It really depends on the type of video.

> The black background in the trimming window behind my actual video to trim feels weird to me, it makes it difficult to understand where the actual edges of my video are, especially if I'm recording something very dark like a terminal session. I think there shouldn't be any background color/image behind my video, but if for some reason there must be one probably a transparency pattern should be used instead.

Yeah, that would be better, but we don't really control the background. @sunshinejr Maybe we could do some view hierchy traversing to set the background color to a [checkerboard NSColor pattern](https://stackoverflow.com/a/32540581/64949)?

> It would be interesting to add the ability to precisely crop the video, as if one is recording a particular window using Mojave's built-in area recording feature it will be difficult to precisely select the correct area.

I think this is outside the scope of Gifski. We don't intend to do advanced video editing. You should just set a crop before recording in your recording app.

> It might be useful to mention a few recommended screen-recording apps in the readme. For instance Mojave's built-in features don't currently allow to easily record only a particular window, a recommended third-party app than can do that would be useful to me for instance.

That is a good idea. I'm working on a plugin for Kap to export to Gifski. I'll mention that and some others when I'm done.

**Comment by sunshinejr** [comment]
@sindresorhus agree with everything you said. The black background indeed is something we do not control, but like with trimming view, we can try to adjust the color by going through the view hierarchy. Should we create a few small tasks from this one and track the progress there?

**Comment by sindresorhus** [comment]
> Should we create a few small tasks from this one and track the progress there?

👍

**Comment by fabiospampinato** [comment]
> I've tried reducing the opacity, but even with 0.7, it doesn't make a difference, and with 0.5 and lower, it looks too washed out.

I see. Maybe filling the entire background, and app icon, with stripes would look better? Maybe using much thicker stripes? Probably not, and you might have tried this [already](https://github.com/sindresorhus/Gifski/issues/25#issuecomment-372763603) 🤔.

> Are there any other Mac apps that has drag and drop that makes it clickable to "open"?

I don't use d&d a lot, but looking at the apps in my dock:

- [Transmission](https://transmissionbt.com): torrents can be dropped but there's also a button for opening one.
- [Affinity Photo](https://affinity.serif.com/en-gb/photo/): d&d and double click to show the open dialog.
- [Tower](https://www.git-tower.com/mac): d&d and button.
- [VSCode](https://code.visualstudio.com): d&d and button available in the "Explorer" activity bar view.

Others are a bit of a stretch:

- [iTerm](https://iterm2.com): d&d for copying a folder's path, no button.
- Finder: folders can be dropped into the tab bar (just learned about this) and there's a button for opening a new tab, which would work kind of like our open dialog.

Pretty much every website that offers some kind of uploading features implements both d&d and a button: imgur, facebook, github, google image search...

IMHO clicking somewhere in the app should open the open dialog, and in general it feels weird that the first window an app opens has no clickable regions at all.

> Yeah... It's not easy to fix. Help welcome!

Unfortunately I don't know anything about macOS native development, and I wouldn't really know how to fix this anyway, perhaps a few random frames of the video could be converted in the background to get a more reliable estimate?

> Yeah, we should normalize the numbers from that slider to the closest whole FPS.

If when dragging the slider a bit nothing changes that would feel weird to me too, in this case I think the slider handler should jump from one whole fps to the next.

> I haven't noticed that, but we'll look into it.

I've timed it and converting a video took ~40s for me over a ~60s estimate, nothing particularly off but for me the countdown seems to be counting down a little faster than it should.

> I think this is outside the scope of Gifski. We don't intend to do advanced video editing. You should just set a crop before recording in your recording app.

I agree that it's probably out of scope. The thing is the OS' built-in video recorder makes it difficult to precisely record a specific window, but this is more of an issue about the built-in recorder than Gifski.

**Comment by fabiospampinato** [comment]
> Maybe filling the entire background, and app icon, with stripes would look better?

Maybe concentric circles could be used instead of stripes, they would make for a better icon and would give the app more of a [target](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBYiFzuoJvwNPUMuR3IFw-8gY6EgPpseT-aCFJ3NpZBwpI61Gc) feeling, perhaps suggesting that files can be ~~thrown at~~ dropped into it.

**Comment by sindresorhus** [comment]
> Clicking somewhere in the initial window should open up the "Open..." dialog, perhaps a button or an icon could be added, or maybe just clicking anywhere in the window should open up the dialog.

There's now an open button in the initial view.

> clicking the cancel button on the conversion window doesn't go back to the trimming window (maybe I changed my mind last-second or with the chosen settings the thing takes forever to process or something).
there's no button for going back from the result window (maybe once looking at the resulting GIF one figures the settings can be tuned better).

This was fixed in the latest version.

> The black background in the trimming window behind my actual video to trim feels weird to me, it makes it difficult to understand where the actual edges of my video are, especially if I'm recording something very dark like a terminal session. I think there shouldn't be any background color/image behind my video, but if for some reason there must be one probably a transparency pattern should be used instead.

This was fixed at some point.

**Comment by sindresorhus** [comment]
> I agree that it's probably out of scope. The thing is the OS' built-in video recorder makes it difficult to precisely record a specific window, but this is more of an issue with the built-in recorder than Gifski.

Check out [Kap](https://github.com/wulkano/kap). It let's you select a window to record. You can then open the recording in Gifski. Kap has a "Open In" option.

> Maybe concentric circles could be used instead of stripes, they would make for a better icon and would give the app more of a target feeling, perhaps suggesting that files can be thrown at dropped into it.

That would not match the Gifski brand: https://gif.ski And I don't think it would look good with a circle there.

> If when dragging the slider a bit nothing changes that would feel weird to me too, in this case I think the slider handle should jump from one whole fps to the next.

This was fixed at some point. The slider now rounds the FPS to a whole number.

**Comment by sindresorhus** [comment]
> I've timed it and converting a video took ~40s for me over a ~60s estimate, nothing particularly off but for me the countdown seems to be counting down a little faster than it should.

Can you reliably reproduce this?

**Comment by sindresorhus** [comment]
Closing as everything was either fixed or has individual issues.

**Comment by fabiospampinato** [comment]
> There's now an open button in the initial view.

I'm on v2.5.0 and I see no button 🤔 

<img width="360" alt="Screen Shot 2020-01-15 at 12 34 37" src="https://user-images.githubusercontent.com/1812093/72434409-6b693a80-3793-11ea-90ae-1ba5745a2b38.png">

> Can you reliably reproduce this?

Yes, I've just tried converting a video with Gifski and at the point where the app said there were 40s left, after about ~60% of the video had been processed already, I started a stopwatch and when the app finished the stopwatch was at ~32s.

**Comment by sindresorhus** [comment]
> I'm on v2.5.0 and I see no button 🤔

It's only on Catalina as it uses SwiftUI.

> Yes, I've just tried converting a video with Gifski and at the point where the app said there were 40s left, after about ~60% of the video had been processed already, I started a stopwatch and when the app finished the stopwatch was at ~32s.

Ok. Thanks for confirming. Could you move it to an individual issue?
