### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by sunshinejr** [sindresorhus/Gifski#112]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/gifski-app/issues/112)

Currently when you cancel the conversion it goes back to the “drop video” controller. We should change that so it goes back to the “edit video” controller.

Additionally we should add back button to the “result” controller, it should also go back to the “edit video” controller.

See #111 for more context.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#133 Feature/improve navigation](https://issuehunt.io/r/sindresorhus/gifski-app/pull/133)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
> Additionally we should add back button to the “result” controller, it should also go back to the “edit video” controller.

I'm thinking a button in this style:

<img width="126" alt="Screenshot 2019-09-04 at 03 10 31" src="https://user-images.githubusercontent.com/170270/64205237-b9a32e80-cec1-11e9-82fd-323bac5d2c0f.png">

**Comment by sunshinejr** [comment]
Looks good @sindresorhus!

**Comment by Ybrin** [comment]
I am looking into it. Is this type of button built in into the macOS APIs or do we need to design it ourselfs?

**Comment by sindresorhus** [comment]
@Ybrin Design it. Shouldn’t be hard to replicate the style using our CustomButton class.
