### ISSUE TITLE
Add `lines` property to Tooltip, alongside `maxWidth`

### ISSUE THREAD

**Issue by sunshinejr** [sindresorhus/Gifski#115]
Currently our `Tooltip` class uses the `maxWidth` property to size itself properly. We want to be able to just specify `lines` instead so it sizes itself based on that (similar to label).

**Comment by sindresorhus** [comment]
It should still be possible to set `maxWidth` though. It can be useful when the content is dynamic. `maxWidth` should take precedence over `lines`.
