### ISSUE TITLE
Crash: "DraggableFile.mouseDragged(with:)"

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#117]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/gifski-app/issues/117)

# The bounty here now applies to https://github.com/sindresorhus/Gifski/issues/118 instead

---

From Crashlytics:

```
# Version: 2.0.0 (18)

Crashed: com.apple.main-thread
EXC_BAD_INSTRUCTION EXC_I386_INVOP 0x0000000000000000
specialized DraggableFile.mouseDragged(with:)

#0. Crashed: com.apple.main-thread
0  Gifski                         0x10a420784 specialized DraggableFile.mouseDragged(with:) + 79 (DraggableFile.swift:79)
1  Gifski                         0x10a420155 @objc DraggableFile.mouseDragged(with:) (<compiler-generated>)
2  AppKit                         0x7fff32c37033 forwardMethod + 211
3  AppKit                         0x7fff32b73367 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 6840
4  AppKit                         0x7fff32b71667 -[NSWindow(NSEventRouting) sendEvent:] + 478
5  AppKit                         0x7fff32a10e6b -[NSApplication(NSEvent) sendEvent:] + 331
6  AppKit                         0x7fff329ff5e0 -[NSApplication run] + 755
7  AppKit                         0x7fff329eeae8 NSApplicationMain + 777
8  Gifski                         0x10a3d4889 main + 6 (AppDelegate.swift:6)
9  libdyld.dylib                  0x7fff613613d5 start + 1
```

Which is this line:

https://github.com/sindresorhus/Gifski/blob/dc29e98daed3d344d6bcc981580bdd0bd102eb2e/Gifski/DraggableFile.swift#L79

But I have no idea why it would crash there and the error message is not very helpful.

Help wanted.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by NehaKushwah993** [comment]
hi, I have been trying to find this issue since last 2 days, but it is not crashing me. Although i have added some check which will prevent it from crash.

But I am not able to create pull request, can you please help me for this?

**Comment by sindresorhus** [comment]
> Although i have added some check which will prevent it from crash.

How can you be sure it fixes the problem if you cannot reproduce it?

> But I am not able to create pull request, can you please help me for this?

https://help.github.com/en/articles/creating-a-pull-request

**Comment by NehaKushwah993** [comment]
Can you send me full crashalytics report? that includes system info n all?

**Comment by sindresorhus** [comment]
Here are the [6 latest Crashlytics reports](https://github.com/sindresorhus/Gifski/files/3582566/Crashlytics.reports.zip).

**Comment by sindresorhus** [comment]
Looks like I fixed this at some point as recent releases doesn't have this crash.
