### ISSUE TITLE
Values in input fields for width and height not editable

### ISSUE THREAD

**Issue by schneiderf** [sindresorhus/Gifski#122]
To reproduce the bug:
- Open application
- Convert a video into a gif
- When finished, open another video to convert without closing application
- Values inside the input fields for width and height are now no longer editable, only by selecting a preset

---
Gifski 2.0.0 (18)
macOS 10.14.6
iMacPro1,1

**Comment by sunshinejr** [comment]
Thanks for filling an issue @schneiderf, we really appreciate it!

@sindresorhus I guess this might be the side effect of our responder chain fixes?
