### ISSUE TITLE
Missing frames

### ISSUE THREAD

**Issue by Garretb1563** [sindresorhus/Gifski#127]
Hello! I am missing frames on the end of my gif when I export with gifski. Example: my gif is 20 frames long, when I export it from gifski it loops with only 18 frames. I can bring it into After Effects also and see how it is shorter than my original composition.

---
Gifski 2.0.0 (18)
macOS 10.14.6
iMac19,1

**Comment by sunshinejr** [comment]
Hey @Garretb1563, can you provide the gif & steps to reproduce the issue and what frames are you missing? would help a lot in investigation.

**Comment by Garretb1563** [comment]
Sure! I'll attach the mp4 file and the final gif and a screenshot of my After Effects comp showing how the gif is shorter than the mp4.

<img width="1028" alt="gifski" src="https://user-images.githubusercontent.com/34348248/63542222-e6cd0580-c4ed-11e9-9846-73dc6b15cc01.png">

**Comment by Garretb1563** [comment]
Here's a link to the mp4 and GIF https://drive.google.com/drive/folders/1fUkDFHz0xaTOxrtA0GVgXx9GgVcgyKTl?usp=sharing

**Comment by sindresorhus** [comment]
@Garretb1563 I have done some improvements that might fix your problem. Could you test this build and let me know? 

[Gifski - build for Garretb1563.zip](https://github.com/sindresorhus/Gifski/files/3912736/Gifski.-.build.for.Garretb1563.zip)

**Comment by sindresorhus** [comment]
I'm going to close this as Gifski 2.6.0 improved how we handle frames.
