### ISSUE TITLE
GIF from a bunch of images

### ISSUE THREAD

**Issue by masture** [sindresorhus/Gifski#128]
---
Gifski 2.0.1 (19)
macOS 10.14.6
MacBookPro14,3

**Comment by kornelski** [comment]
I'm not sure how doable it is for the GUI, but you can do it from the command line version https://gif.ski/

**Comment by Ybrin** [comment]
Dragging and dropping multiple files could open a customized view where you can arrange the images instead of cutting the video file.
The question is do we want to support it or not.

**Comment by sindresorhus** [comment]
I doubt we'll add this. It would require a lot of UI work to arrange the images, set delays, etc, for an uncommon use-case. However, I think we should add a `ffmpeg` command to the readme on how to make a ProRes video from a bunch of images, that can then be passed to Gifski.
