### ISSUE TITLE
Make non-looping GIF

### ISSUE THREAD

**Issue by schneiderf** [sindresorhus/Gifski#137]
Feature request: I would like to have the option to make non-looping gifs. Adobe Photoshop for example offers that option in its legacy "Save for web" exporter. Would be really great to see, thank you!

---
Gifski 2.0.1 (19)
macOS 10.14.6
iMacPro1,1

**Comment by sindresorhus** [comment]
We should add a checkbox for "Infinite loop" and a text field (disabled by default) that when "Infinite loop" is unchecked, you can specify a loop count.

**Comment by sunshinejr** [comment]
@sindresorhus I only found an option to add a flag `--once` to the gifski cli to remove looping the gif. Do you think we could start with just a checkbox if it's infinite or not? Loop count might be more time-consuming.

**Comment by kornelski** [comment]
I expose only `once: bool` flag, because anything in between seems niche.

**Comment by sindresorhus** [comment]
Yeah, lets go with only a checkbox. Loop count is indeed too niche.
