### ISSUE TITLE
Update lib gif.ski

### ISSUE THREAD

**Issue by kornelski** [sindresorhus/Gifski#174]
In 0.10 I've changed interface from taking frame delay, to taking absolute time in seconds (float) when the frame should be presented (aka PTS). This makes the library manage delays internally and it supports arbitrary framerates.

If you pass PTS straight from the codec, it'll give smoothest framerate. See how to limit fps in a PTS-friendly way: https://github.com/ImageOptim/gifski/commit/f1e8b59039999c7a577f3c437e4e7c61a4780f4c#diff-fbfbc756b97d21883f66ee9308049c58R79

cc #173

**Comment by sindresorhus** [comment]
Awesome!

> If you pass PTS straight from the codec, it'll give smoothest framerate.

That's only true if the user chooses the same FPS in Gifski as the video FPS, right?

Also not really sure how to get the PTS with AVFoundation. I think this would be good as a follow-up issue as it's not straight forward and not something I have time to work on right now.

Some resources:
- https://stackoverflow.com/a/39650953/64949
- https://stackoverflow.com/a/6474313/64949
- https://stackoverflow.com/a/39681999/64949
- https://stackoverflow.com/questions/48485983/how-to-get-the-timestamp-of-each-video-frame-in-ios-while-decoding-a-video-mp4
- https://forums.developer.apple.com/thread/119613

**Comment by kornelski** [comment]
actualTime.seconds seems like it's the PTS from the codec.
