### ISSUE TITLE
Looping in the editor should loop only in the selected area

### ISSUE THREAD

**Issue by silvenon** [sindresorhus/Gifski#184]
After the last update the video playback in the editor started looping when "Loop forever" is checked, _which is awesome_, I just think that it makes more sense to only loop within the selected area. Currently looping starts from the beginning of the video.

**Comment by sindresorhus** [comment]
That's a bug. When implementing the feature, I forgot to check trimming from the start. I only tried trimming from the end. I'll fix this soon.
