### ISSUE TITLE
Libgifski doesn't always call the progress callback the expected number of times

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#187]
With [Odd width.mp4.zip](https://github.com/sindresorhus/Gifski/files/4435884/Odd.width.mp4.zip)

@kornelski Notice here how there are 17 frames, 17 frames are added to Gifski, but `gifski_set_progress_callback` is only called 16 times.

```
Frames: [0.0, 0.058333333333333334, 0.11666666666666667, 0.175, 0.235, 0.29333333333333333, 0.3516666666666667, 0.4116666666666667, 0.47, 0.5283333333333333, 0.5866666666666667, 0.6466666666666666, 0.705, 0.7633333333333333, 0.8233333333333334, 0.8816666666666667, 0.94]
Frame count: 17
Added frame count: 1
Added frame count: 2
Added frame count: 3
Added frame count: 4
Added frame count: 5
Completed unit count: 1
Added frame count: 6
Completed unit count: 2
Added frame count: 7
Completed unit count: 3
Completed unit count: 4
Added frame count: 8
Added frame count: 9
Completed unit count: 5
Added frame count: 10
Completed unit count: 6
Added frame count: 11
Completed unit count: 7
Added frame count: 12
Completed unit count: 8
Added frame count: 13
Completed unit count: 9
Added frame count: 14
Completed unit count: 10
Added frame count: 15
Completed unit count: 11
Added frame count: 16
Completed unit count: 12
Added frame count: 17
Completed unit count: 13
Completed unit count: 14
Completed unit count: 15
Completed unit count: 16
```

You can reproduce this in the https://github.com/sindresorhus/Gifski/tree/missing-progress-events branch.

**Comment by kornelski** [comment]
gifski doesn't write all the frames you give it. If timestamps of two frames differ by less than 1ms, then they're the same frame to GIF, so only one of them is written.

**Comment by sindresorhus** [comment]
> I'm not sure how to solve that. I suppose I could detect skipped frames and emit fake progress events for them.

That or include a parameter in the callback with the completed frame count. I prefer fake progress events though.

**Comment by kornelski** [comment]
Ok, fixed in master
