### ISSUE TITLE
QGIS 3.12 crashing

### ISSUE THREAD

**Issue by gideonsway** [sindresorhus/Gifski#191]
I have recently installed QGIS 3.12 on my Macbook which is running High Sierra. But QGIS is crashing. The crash report states that "DYLD, [0x4] Symbol missing". I am not tech but having checked there seems talk of X-code problem. I know this has been covered before, but the answers seem way above my pay grade. Is there an idiots guide please - ie do this, do this etc. Thanks

**Comment by kornelski** [comment]
Wrong project? I don't see how QGIS is related to Gifski.
