### ISSUE TITLE
Couldn't encode media

### ISSUE THREAD

**Issue by agustif** [sindresorhus/Gifski#198]
i tried to convert an mp4 generated with Kap.app with no luck.

Any ideas?

**Comment by sindresorhus** [comment]
Not much information here for us to work on. Does it happen every time? Can you confirm you're on the latest Gifski and Kap version?

**Comment by agustif** [comment]
Just installed Gifski from App Store right now.

The video was generated a few months back with Kap. will try with a fresh now after updating and report back!

**Comment by sindresorhus** [comment]
Bump. Would be great if you could share a recording that reproduces the issue.

**Comment by agustif** [comment]
Hello @sindresorhus I just updated gifski, although It's not the same exact video another mp4 generated by Kap.app
brings this error

![Uploading Captura de pantalla 2020-10-18 a las 12.39.27.png…]()



here's the file
https://imgur.com/a/KorPdbn
