### ISSUE TITLE
Show warning when framerate is set above 50 fps

### ISSUE THREAD

**Issue by phaseOne** [sindresorhus/Gifski#200]
Due to the fact that nearly all browsers—still to this day—only support a maximum frame delay of 20 ms, GIFs exported at 60 fps (16 ms frame delay) will render at 10 fps (100 ms frame delay) in a browser. Finder happily plays back short frame delay GIFs, so I was mislead into thinking this would work on the internet, or in my case Slack.

It seems there's a use case for exporting GIFs with a framerate above 50 fps (see #161), so I think we should display a warning to the user if they exceed this 50 fps limit, and maybe even convert this into a snapping UISlider.
<img alt="CleanShot 2020-08-07 at 13 14 14@2x" src="https://user-images.githubusercontent.com/1310985/89684830-0d777e00-d8b0-11ea-9c74-40f54e8b3919.png" height="133"/>

<img alt="Gifski Warning Mockup" src="https://user-images.githubusercontent.com/1310985/89696892-9dc4bb80-d8ce-11ea-8e7d-378420e9fa45.jpg" height="400"/>

What do you all think of the copy in the warning message and the general approach?

**Comment by phaseOne** [comment]
Following up with a slightly modified UI that introduces a surface for users to re-trigger the warning in the event they dismiss it by clicking away.

<img alt="Gifski Warning Mockup v2" src="https://user-images.githubusercontent.com/1310985/89699076-84753c80-d8d9-11ea-81ae-832cce48cc7d.jpg" height="400" />

**Comment by kornelski** [comment]
Simplest solution would be to cap fps at 50.

**Comment by sindresorhus** [comment]
@kornelski I thought libgifski did the alternating frame delay trick to support 60 FPS. Or did we just talk about it but it was not implemented?

**Comment by kornelski** [comment]
Alternating frame delays are implemented and allow GIF to approximately specify any framerate it wants. That's separate from browsers actually honoring the choice. 60fps requires at least some frames to have delay=1, which isn't supported.
