### ISSUE TITLE
Change the speed of the GIF

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#201]
A few people have requested this over email and some other GIF tools have this too.

---

**This issue requires you to have advanced Swift knowledge. It's not an easy beginner issue.**

**Comment by fawkeswei** [comment]
Would be super useful for me

**Comment by janbrasna** [comment]
I can imagine a very lengthy screen recording that would benefit from speeding up, or the opposite… making the interaction/animation slower to better make a point. So it's not a bad idea at all!

**Comment by codeclown** [comment]
I usually need to speed up gifs I make for Twitter/GitHub ([example](https://github.com/codeclown/helppo/blob/master/docs/screenshots/readme_intro.gif)). Currently I use ffmpeg as an intermediate step, but it would be super nice to have the option directly in Gifski.

**Comment by alexkaessner** [comment]
I recently also had the case I wanted to share a relatively lengthy screen recording. To speed things up **and** save frames (hence file size), I wanted to speed the GIF up by 2×. Speeding the video up was better in this case compared to lower the frame rate to something like 5-10 fps. I ended up converting the video with Compressor and then created the GIF with Gifski.

**Comment by sindresorhus** [comment]
This is now "PR welcome".

**Comment by sindresorhus** [comment]
This is now out: https://apps.apple.com/app/id1351639930
