### ISSUE TITLE
Failed to generate frame: Cannot Decode

### ISSUE THREAD

**Issue by Oleg-Chashko** [sindresorhus/Gifski#202]
macOS v.11.0 Beta (20A5364e)
Gifski v.2.9.0 (39)

**Screenshot:**
<img width="476" alt="Bildschirmfoto 2020-09-10 um 16 26 45" src="https://user-images.githubusercontent.com/62497891/92745237-7906ac80-f382-11ea-806b-99d2954212a0.png">

**Video recording:**
[Bildschirmaufnahme 2020-09-10 um 16.18.34.zip](https://github.com/sindresorhus/Gifski/files/5202315/Bildschirmaufnahme.2020-09-10.um.16.18.34.zip)

**Comment by sindresorhus** [comment]
Thanks for reporting. Are you able to reproduce it again if you convert with the exact same file and settings? What settings did you convert with (can you take a screenshot)? I was not able to reproduce this myself.

**Comment by kornelski** [comment]
I've got the same error on a screen recording from Big Sur. I fails on a specific frame, every time. I can trim the problematic frame out of the animation, and it won't fail then.

**Comment by Oleg-Chashko** [comment]
@sindresorhus 
This is a problem only on Big Sur. 
Sometimes it freezes, you have to unload it forcibly. But this rarely happens.
[Test 1.zip](https://github.com/sindresorhus/Gifski/files/5214090/Test.1.zip)
[Test 2.zip](https://github.com/sindresorhus/Gifski/files/5214091/Test.2.zip)

**Comment by kornelski** [comment]
This is the error: (AVFoundationErrorDomain Code=-11821)

https://stackoverflow.com/questions/26209099/error-domain-avfoundationerrordomain-code-11821-cannot-decode

**Comment by sindresorhus** [comment]
> Perhaps it's trying to say there's no frame at the given timestamp? In that case I suppose it'd be safe to skip the frame.

No, that's a different error, and we're already handling that: https://github.com/sindresorhus/Gifski/blob/276042508e10e15413a34a4667e0f7f6fe383ad6/Gifski/Utilities.swift#L342

**Comment by sindresorhus** [comment]
The error code is the error `AVErrorDecodeFailed`.

---

Handy tool: https://www.osstatus.com/search/results?platform=all&framework=all&search=-11821

**Comment by kornelski** [comment]
Apple's documentation is useless: https://developer.apple.com/documentation/avfoundation/averror/averrordecodefailed

but the StackOverflow answer mentions they've solved it by correcting their timestamps, so I suspect this may be another case of AV getting confused by a mismatched timestamp.

**Comment by sindresorhus** [comment]
Some observations. I'll look more into this when the final macOS 11 release is out.

It seems to only fail at the following timestamps (Test 1):

```
Decode failed at time: 0.13666666666666666
Decode failed at time: 0.17166666666666666
Decode failed at time: 0.20666666666666667
Decode failed at time: 0.24
Decode failed at time: 0.275
Decode failed at time: 0.3433333333333333
Decode failed at time: 0.37833333333333335
Decode failed at time: 0.41333333333333333
```

The error does not happen if I remove https://github.com/sindresorhus/Gifski/blob/276042508e10e15413a34a4667e0f7f6fe383ad6/Gifski/Gifski.swift#L174-L175

It also doesn't happen with:

```swift
generator.requestedTimeToleranceBefore = CMTime(seconds: 0.3, preferredTimescale: .video)
generator.requestedTimeToleranceAfter = CMTime(seconds: 0.3, preferredTimescale: .video)
```

However, it does fail with `0.2` seconds. Also, we cannot have this much of a tolerance as then it wouldn't be very accurate.

If there's no other solution, we could consider ignoring any decode errors for the first 0.5 seconds. I would really like to find a better solution though.

**Comment by sindresorhus** [comment]
> so I suspect this may be another case of AV getting confused by a mismatched timestamp.

What do you mean by mismatched timestamps? `AVAssetImageGenerator` is supposed to be able to handle any timestamp that is within the range of the video, even if it doesn't match up with the actual frames.

**Comment by kornelski** [comment]
Oh, I forgot the framework promises to support any timestamp. I thought it could fail if you asked for a timestamp that doesn't correspond to a frame (but maybe that still happens despite the API promise).

**Comment by aheze** [comment]
Similar problem here.

![Screen Shot 2020-12-11 at 9 28 52 AM](https://user-images.githubusercontent.com/49819455/101935083-5bb8c880-3b93-11eb-9faa-767c1a1f2be4.png)

Here is the mov file:

[always.mov.zip](https://github.com/sindresorhus/Gifski/files/5680649/always.mov.zip)

I am on Big Sur 11.0.1 on Apple silicon.

**Comment by sindresorhus** [comment]
@aheze Can you try upgrading to macOS 11.1 and then try rerecording and converting? I read in the release not that it fixes an issue with scree recordings.

**Comment by aheze** [comment]
@sindresorhus just updated and tried the same video file, but got the same crash

**Comment by sindresorhus** [comment]
@aheze 

> then try rerecording

Because this is most likely a bug in the screen recorder that creates invalid videos.

**Comment by aheze** [comment]
Ah. That's probably the problem, I was using xcrun to screen record the simulator...

**Comment by sindresorhus** [comment]
This is the release note item I was talking about:

> simctl video recordings no longer cut off the end of the video when no screen updates are happening. The recording timeline now holds the last frame and extends until you terminate the recording with Control-C (SIGINT). (67952344) (FB8565355) - https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-12_3-release-notes

**Comment by aheze** [comment]
@sindresorhus Hmm. My Xcode is still on 12.2, I'll try updating.
