### ISSUE TITLE
Cannot convert video with dimensions of 10x60px

### ISSUE THREAD

**Issue by jussivirtanen** [sindresorhus/Gifski#203]
I was trying to convert a small mp4 video file to gif, but got the following error message:
![gifski](https://user-images.githubusercontent.com/3430121/93598975-1dfa3880-f9c6-11ea-990d-3243f13575df.png)
The video file I tried to convert is this: https://www.dropbox.com/s/kfwbext1imy10jb/type-indicator-new.mp4?dl=0. Any ideas what's wrong here?

Thank you for the app, it's been working great so far!

**Comment by sindresorhus** [comment]
It's gonna be a month until the next release, but here's a build with the fix: [Gifski.app.zip](https://github.com/sindresorhus/Gifski/files/5248292/Gifski.app.zip)

(You need to open it by right-clicking and select "Open")

**Comment by jussivirtanen** [comment]
Thanks for this fix and your quick reply @sindresorhus 👏🏻🙏🏻
