### ISSUE TITLE
Multiple slice ranges > multiple outputs

### ISSUE THREAD

**Issue by dxcore35** [sindresorhus/Gifski#208]
My user case is to make more then one gif file from video.
- make the window bigger so the user can put more then one slicer range
- after placing as many as we wish slicers ranges, the software will export multiple gifs

---
Gifski 2.9.1 (40) - com.sindresorhus.Gifski
macOS 10.15.0
MacBook10,1

**Comment by sindresorhus** [comment]
Sorry to disappoint, but this is outside the scope of Gifski. Gifski is really just a good video to GIF converter. We added a small editor for convenience, but I don't want (nor have time) to add advanced editing functionality or a batch workflow. Your use-case of exporting multiple GIFs from a single video is not very common either.

I would recommend using a proper video editing app for slicing the video into the parts you need and then you can run those clips through Gifski.
