### ISSUE TITLE
Full Apple Silicon support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#215]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2472.8%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/gifski-app/issues/215)

I currently get this warning:

> ld: warning: ignoring file /Users/sindresorhus/Library/Developer/Xcode/DerivedData/Gifski-covufrfbnkqrunfagfxjgrfngrhp/Build/Intermediates.noindex/ArchiveIntermediates/Gifski/BuildProductsPath/target/release/libgifski.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $72.80)

- [<img src='https://avatars1.githubusercontent.com/u/170270?v=4' alt='sindresorhus' width=24 height=24> sindresorhus](https://issuehunt.io/u/sindresorhus) ($72.80)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by kornelski** [comment]
When compiling libgifski you need to add `--target=aarch64-apple-darwin` to `cargo build` and it'll build `target/aarch64-apple-darwin/release/libgifski.a` compatible with Apple Silicon. That may require some wrangling with the xcode project file.

**Comment by sindresorhus** [comment]
So we need two different build configurations in `Vendored/gifski.xcodeproj`? And then we need the `Gifski.xcodeproj` to pick the correct `libgifski.a` based on the platform?

I'm not familiar with Rust and how the build stuff works, so I'm going to leave this for someone else.

---

I did try adding the build flag and:

```
❯ rustup target add aarch64-apple-darwin
error: toolchain 'stable-x86_64-apple-darwin' does not contain component 'rust-std' for target 'aarch64-apple-darwin'
```

And it stopped there.

**Comment by kornelski** [comment]
I think the Apple Silicon support in Rust is still pre-release, so until it makes it to a stable version, you first need `rustup default nightly`.

Xcode supports per-architecture variables:

<img width="557" alt="vars" src="https://user-images.githubusercontent.com/72159/98608560-60176a80-22e3-11eb-8531-057276730cbf.png">

so perhaps this could be injected into xcode config somehow?

**Comment by sindresorhus** [comment]
`rustup target add aarch64-apple-darwin` now works.

**Comment by lostdesign** [comment]
@sindresorhus there still is a fund on this issue. Just letting you know.
