### ISSUE TITLE
Dark green flicker in background

### ISSUE THREAD

**Issue by fiendish** [sindresorhus/Gifski#226]
This gif was made with macOS built-in screen recording to .mov and then drag/drop onto gifski. It shows a weird green flicker.

![Screen Recording 2021-02-03 at 12 36 51 PM](https://user-images.githubusercontent.com/201996/106800061-3be6d380-661d-11eb-9d1a-e08d5013d7a3.gif)

---
Gifski 2.13.0 (45) - com.sindresorhus.Gifski
macOS 10.14.6
MacBookPro14,3

**Comment by sindresorhus** [comment]
Can you try this build and see if it fixes the problem? https://github.com/sindresorhus/Gifski/files/5888842/Gifski.app.zip

**Comment by fiendish** [comment]
It doesn't appear to run. On first try I get the normal "Are you sure you want to open this?" message from macOS, and when I say yes nothing happens afterward.

**Comment by sindresorhus** [comment]
@fiendish Weird. It works fine for me. Can you try this build then? https://github.com/sindresorhus/Gifski/files/5921271/Gifski.app.zip

Would you also be able to share the source video so I can reproduce and look into the issue?

**Comment by fiendish** [comment]
Ah, they work when I put them in my Application folder. Wasn't running from Downloads. 🤷‍♂️ 

Both builds work. Here is the original for future regression testing: 

https://user-images.githubusercontent.com/201996/106912097-ef080900-66bf-11eb-845a-d40ff1436971.mov

**Comment by sindresorhus** [comment]
This is now fixed in the latest Gifski version. Just go to https://apps.apple.com/no/app/gifski/id1351639930?mt=12 and click "Update".
