### ISSUE TITLE
Freezes during conversion when using 50fps or Trim

### ISSUE THREAD

**Issue by Oleg-Chashko** [sindresorhus/Gifski#230]
- macOS Big Sur v.11.2 (20D64)
- Gifski v.2.13.1 (46)

**Screen Recording: 50fps**

https://user-images.githubusercontent.com/62497891/107151531-598ca380-6963-11eb-843b-b5ce5aa074a5.mov

**Screen Recording: Trim**

https://user-images.githubusercontent.com/62497891/107151578-9c4e7b80-6963-11eb-8cc9-98542fc98fd7.mov

**Test file**
[Test file.zip](https://github.com/sindresorhus/Gifski/files/5939282/Test.file.zip)

**Comment by sindresorhus** [comment]
Thanks for reporting. I think this will be fixed in the next version. It fixed it for me. Could you try and confirm?

https://github.com/sindresorhus/Gifski/files/5937337/Gifski.app.zip

**Comment by Oleg-Chashko** [comment]
I am glad to help. 
- Trim bug - Fixed. 😀 
- 50fps bug - Not fixed. 🙁
<img width="472" alt="Screen Shot 50fps" src="https://user-images.githubusercontent.com/62497891/107158461-78eaf700-698a-11eb-8a3d-3c9804703884.png">
