### ISSUE TITLE
Produces empty GIF for very short video

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#231]
@kornelski https://github.com/sindresorhus/Gifski/pull/222 introduced an issue where this video produces an empty invalid file: [Short.mp4.zip](https://github.com/sindresorhus/Gifski/files/5950638/Short.mp4.zip)

Before this change:

![Short](https://user-images.githubusercontent.com/170270/107351122-d30bc980-6afc-11eb-960f-a85488ab0673.gif)

After:

[Short.gif.zip](https://github.com/sindresorhus/Gifski/files/5950674/Short.gif.zip)

---

I realize the video is way too short and weird, but we should never produce an invalid GIF. According to logging, it successfully generated 2 frames and passed them to libgifski.

**Comment by kornelski** [comment]
Fixed in https://github.com/ImageOptim/gifski/commit/2f62fbecf57430d3d5b88c817378b570be2c9740
