### ISSUE TITLE
Rounded corners at the bottom of the window 

### ISSUE THREAD

**Issue by siamos93** [sindresorhus/Gifski#233]
Hello, 
I have an export problem on mac os (Big Sur 11.2.1).
In my gif export, I have 2 rounded corners that appear at the bottom left and right. Is there a way to remove them?
The rendering is not great when I import it into Behance for example.

And well done and thank you for this great and very useful application! 

Thx, 
<img width="992" alt="screen" src="https://user-images.githubusercontent.com/47351643/108195776-89346c00-7118-11eb-8bf6-7bdae4a5cf8a.png">

**Comment by sindresorhus** [comment]
Gifski should not add rounded corners. Would you be able to share the source video so I could reproduce? Most likely the source video has rounded corners too.

**Comment by siamos93** [comment]
I first exported directly to XD. Are the rounded edges coming from there?

**Comment by kornelski** [comment]
Does the video format support transparency? Some formats like VP9 do.

**Comment by siamos93** [comment]
Hello @kornelski I don't know, few export settings for Adobe XD… The prototype is saved directly in .mp4 format. I do not know if this problem exists on PC or if it is specific to the windows of the ios interface with its rounded edges ...

**Comment by kornelski** [comment]
@siamos93 There's 99.99% chance that the GIF looks exactly like your exported video, i.e. you've exported a video that has black rounded edges.

**Comment by siamos93** [comment]
Yes that's what I'm telling myself. I'll have to dig on the XD side ;-p Thanks to you anyway!
