### ISSUE TITLE
Rewrite parts of Gifski in SwiftUI

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#244]
Some things that could independently be rewritten in SwiftUI:

- [ ] The initial drop view.
- [ ] Edit window (or smaller parts of it):
	- [x] File size estimate
	- [ ] Video player / trimmer
	- [ ] GIF settings
- [ ] The conversion progress (should be much simpler to implement in SwiftUI)
- [ ] Conversion completed screen
- [ ] `CheckerboardView` (using `SwiftUI.Canvas`)
	(I have this one already done in another app. So I'll add it here when we can target macOS 12)

The priority is the editor view as it would be much simpler with SwiftUI.

---

This is not an easy issue and requires advanced Swift and SwiftUI knowledge.

**Comment by ben-p-commits** [comment]
@sindresorhus - I've started playing with a rewrite of `ConversionCompletedViewController` in SwiftUI.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/5067237/205092702-85a98c20-6660-47e9-a730-2f5fb24cf643.png">

How perfect do you expect the layout to mirror the NSViewController / nib version of the UI? Some of the button styles used in the nib differ from the SwiftUI defaults.

**Comment by sindresorhus** [comment]
Nice! I would prefer if we could get as close as possible to the existing one, including animations.

As for the button styles at the top, I guess we could use https://github.com/siteline/SwiftUI-Introspect to set the correct style.

**Comment by sindresorhus** [comment]
By the way, I intend to target macOS 12 soon, so you can just set that as the target and use anything new there. It may make some things easier.

https://www.wwdcnotes.com/notes/wwdc21/10018/

**Comment by ben-p-commits** [comment]
Oh excellent, that saves me some pain :)
