### ISSUE TITLE
End frames dropped if they're the same

### ISSUE THREAD

**Issue by apkelly** [sindresorhus/Gifski#247]
Hi,

I have a video that shows an animation that comes to rest in a final state and the video shows that final state for 2-3 seconds. However, when this video is converted to a .gif, the final state is only shown for a single frame. I'd like the gif to be as long as the video without it truncating duplicate frames at the end.

Or at least give me a checkbox to allow me to preserve all the frames if this behaviour is an optimisation in the app.

Here is the source and output showing what I mean.

https://user-images.githubusercontent.com/2559953/124855986-23744e00-dfed-11eb-8479-a275ef0da2e3.mp4
https://user-images.githubusercontent.com/2559953/124855971-1a837c80-dfed-11eb-8f56-ead0898ec449.gif

**Comment by sindresorhus** [comment]
There's unfortunately a bug in macOS 11 where videos with few key frames fail to decode many frames. This is completely out of our control. We plan to move to a different way to generate the frames, but it's a lot of work, so will take some time: https://github.com/sindresorhus/Gifski/issues/229

A quick workaround is to export with a higher frame rate and use ProRes. If you cannot re-export, you could convert the video with a video converter app like [Permute](https://apps.apple.com/us/app/permute-3/id1444998321?mt=12).

I just tried converting the video you shared to ProRes and it then worked just fine with Gifski:

![124855986-23744e00-dfed-11eb-8479-a275ef0da2e3 2](https://user-images.githubusercontent.com/170270/125160852-6aa73e00-e1a9-11eb-91ea-903b601f6646.gif)

**Comment by sindresorhus** [comment]
This was fixed in Gifski v2.17.0: https://apps.apple.com/app/id1351639930
