### ISSUE TITLE
Transparent colors are duplicated in ver1.4.0

### ISSUE THREAD

**Issue by gifars112** [sindresorhus/Gifski#249]
Transparent colors are duplicated in ver1.4.0.
This is inconvenient when editing gifs.
![sakura_2021-07-28_22-18-05](https://user-images.githubusercontent.com/88094418/127329133-0f3f548b-4daf-46ce-9a0d-09158b14c19b.jpg)

**Comment by sindresorhus** [comment]
You are using a very old version of Gifski. Try upgrading.

**Comment by kornelski** [comment]
BTW, this is not a duplicate color. If a color is designated as transparent, its palette entry is unusable, so another palette entry must be used to have this color as opaque.
