### ISSUE TITLE
Linux GUI support?

### ISSUE THREAD

**Issue by arduinka55055** [sindresorhus/Gifski#250]
i know, it is macos only. but macos is almost like linux, so there's posix, and you probably can port it painlessly

what do you think?

**Comment by kornelski** [comment]
It doesn't work like that, unfortunately. The GUI tookit that macOS uses is Apple's proprietary, and not available on any other platform.

However, the command-line version (https://gif.ski) works on Linux just fine.

**Comment by arduinka55055** [comment]
Ok, thanks. your project is good anyways.
