### ISSUE TITLE
Duration of time

### ISSUE THREAD

**Issue by Angelk90** [sindresorhus/Gifski#252]
Hi @sindresorhus , in addition to knowing the estimated size, it would also be possible to know how long the video lasts after editing.

https://user-images.githubusercontent.com/20476002/133589612-3617b60d-c784-409d-9d9e-a068e836252a.mov

**Comment by sindresorhus** [comment]
That's a very good point. I'm surprised no one else has requested this.

Where in the UI would you want to see the duration?

**Comment by Angelk90** [comment]
@sindresorhus : Maybe before or after Estimated size?

**Comment by sindresorhus** [comment]
I was thinking either there or below "Loops:", because there's space there. I'll play with it when I have some time.

**Comment by sindresorhus** [comment]
This is now available: https://apps.apple.com/no/app/gifski/id1351639930?mt=12
