### ISSUE TITLE
Support lower quality

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#26]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24200%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/gifski-app/issues/26)

High-quality is awesome, but sometimes I need to use this for longer clips.

@kornelski Is there any way we could support a lower quality mode? I know we have a quality slider, but even with it at 0%, the file is huge.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $200.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($200.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by kornelski** [comment]
Yea, files can be made smaller. 

The existing quality setting isn't really that good for reducing file size. It just happens a little bit as a side effect of making it uglier.

Bigger reduction could be from reducing movement in the animation, especially cropping area that changes between the frames. I'll look into it.

And ideally it should use giflossy. That gives easy 50% reduction with less quality loss. Unfortunately, that can't be in the App Store, because Apple requires giving them a distribution license on terms that more restrictive than GPL permits, and I don't own full copyright to gifsicle to grant Apple such rights.

**Comment by sindresorhus** [comment]
`giflossy` has an alternative license which we comply with:

> The following alternative license may be used at your discretion.

> Permission is granted to copy, distribute, or alter Gifsicle, whole or in part, as long as source code copyright notices are kept intact, with the following restriction: Developers or distributors who plan to use Gifsicle code, whole or in part, in a product whose source code will not be made available to the end user -- more precisely, in a context which would violate the GPL -- MUST contact the author and obtain permission before doing so.
> \- https://github.com/kohler/gifsicle#copyrightlicense 

I read that as it's fine to distribute `giflossy` as long as the source is available, which it is.

**Comment by kornelski** [comment]
That is under a condition that the author agrees to grant alternative license (the MUST part three)

In the App Store Apple is the distributor and they explicitly refuse to comply with the. GPL.

**Comment by sindresorhus** [comment]
Can we ask the author then?

**Comment by sindresorhus** [comment]
@kornelski Is there anything else we can use to reduce the file size other than `giflossy`? I have tried both mentioning `@kohler` here and emailing him without any response.

**Comment by kornelski** [comment]
Well, lossy compression is most effective and tackles the problem directly.

Indirectly, the solution is to reduce amount of changes in the video.

For inputs in lossy video formats, some form of denoising (e.g. median filter) should be helpful.

For real-life videos temporal denoising could help. Also video stabilization would be a great improvement.

**Comment by kohler** [comment]
If *you* are making the source code available, it doesn't matter whether or not *Apple* does.

**Comment by kornelski** [comment]
@kohler App Store T&Cs directly forbid use of code that author can't license to Apple under closed-source terms. Apple intentionally refuses to take any GPL code, regardless of whether it'd be compliant or not (also, it's not compliant: https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement)

**Comment by kohler** [comment]
As long as the Gifski product’s source code is entirely available to the end user, you don't need my permission; the alternative license explicitly allows you to include Gifsicle. I can see the confusion around “more precisely, in a context that would violate the GPL” but this seems fine to me.

**Comment by kornelski** [comment]
I'll take it as a confirmation that you agree to distribute gifsicle in the App Store, on terms of Apple Developer Program License Agreement.

**Comment by kohler** [comment]
I confirm that it is OK to distribute Gifsicle on a product whose source code is freely available via an open-source license, specifically in this case one compatible with the BSD license, and that is also available via the App Store.

The product’s source code must be freely available via an open-source license.

**Comment by sunshinejr** [comment]
Awesome. Thanks so much for this @kohler. So now the plan would be to stop using the quality parameter in `libgifski` and, instead, use `gifsicle --lossy`.

**Comment by DeveloperBen** [comment]
I can work on this if no one else is working on this

**Comment by kornelski** [comment]
I'm working on this

**Comment by kornelski** [comment]
:shipit: https://github.com/ImageOptim/gifski/releases

**Comment by sunshinejr** [comment]
@kornelski that's awesome 🚀 do you also want to finish it on the client side? seems like we would need to pass the flag only, as you are [properly calculating the quality anyways](https://github.com/ImageOptim/gifski/blob/d8357dec3608f9d9de6426c44907442aea62a2cf/src/lib.rs#L65-L75), right?
