### ISSUE TITLE
Artifacts on full quality

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#265]
![Screen Recording 2022-01-14 at 00 35 56](https://user-images.githubusercontent.com/170270/149381118-08881936-9e1e-426e-9374-568f4b464a83.gif)

Source: https://user-images.githubusercontent.com/170270/149381146-d0fd1322-fc12-41d9-a868-04a975d7457a.mov

// @kornelski

**Comment by sindresorhus** [comment]
With Gifski 2.19.0 (before the gif.ski upgrade):
![Screen Recording 2022-01-14 at 00 35 56](https://user-images.githubusercontent.com/170270/149381533-5054f094-4f63-46bc-b40a-9a19855af2de.gif)

**Comment by kornelski** [comment]
Ouch.

**Comment by kornelski** [comment]
Fixed
