### ISSUE TITLE
Alpha channel not preserved with low quality

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#267]
Got a report from a user that the alpha channel is not preserved. I can reproduce when the quality is set to less than 30%. This is a regression from Gifski 2.19.0 (before the gif.ski upgrade).

#### Gifski (main branch)

![Long Press-cropped-comp](https://user-images.githubusercontent.com/170270/149871033-d270ca35-6e1b-446e-8d7d-7c984f585654.gif)

#### Gifski 2.19.0 (older version)

![Long Press-cropped-comp](https://user-images.githubusercontent.com/170270/149870896-4992c1e2-b929-471a-835b-942d7afc6f87.gif)

---

Source: https://user-images.githubusercontent.com/170270/149871168-e562bc7a-b37e-4db7-86a7-5377d064669c.mp4

---

// @kornelski

**Comment by sindresorhus** [comment]
Another fixture. This one just shows a one frame flash (but that's a regression too).
![puppets_with_alpha_hevc](https://user-images.githubusercontent.com/170270/149871441-3d02fd3a-e3f9-44ac-bb75-22502224e8bb.gif)


https://user-images.githubusercontent.com/170270/149871462-572e4082-7f83-494e-a4fe-5e44e7a7724c.mov

**Comment by kornelski** [comment]
Fixed in eeaa53c9d2361087246543c3cd1bb9f294eafc3d

**Comment by sindresorhus** [comment]
Confirmed fixed. Thanks for the quick fix.
