### ISSUE TITLE
Gifski v1.6.3 | There is a big problem with synthesizing pictures of transparent channels

### ISSUE THREAD

**Issue by Jdb156158** [sindresorhus/Gifski#268]
[source material.zip](https://github.com/sindresorhus/Gifski/files/7895885/source.material.zip)

Boss, after I use gifski to synthesize the above pictures to generate GIF, the color values of GIF pictures are disordered. I test that it will appear only when the material background is transparent in a large area.

Operation steps:
gifski --repeat 1 --fps 1 -o anim. gif IMG*. png

Gifski version:
v1.6.3

Thank you very much and look forward to your solution

**Comment by sindresorhus** [comment]
@Jdb156158 This is the issue tracker for the Gifski Mac app. Can you open your issue on https://github.com/ImageOptim/gifski instead?
