### ISSUE TITLE
Missing frames

### ISSUE THREAD

**Issue by egorpezdir** [sindresorhus/Gifski#270]
Hello, so i exported a png sequence with transparent background (its an object disappearing) and gifski seems to be skipping the end frames where the image is completely transparent. What can i do?

**Comment by kornelski** [comment]
Does it also happen with the command line version of gifski?

Can you share the PNG images to reproduce the issue?

**Comment by egorpezdir** [comment]
> Does it also happen with the command line version of gifski?
i am using the command line version (_gifski -o output.gif frame*.png_)



> Can you share the PNG images to reproduce the issue?
[here](https://drive.google.com/drive/folders/1CwoJdxu2Rb2FBTJ6H4rdk0B6vUf2SEsR?usp=sharing)

**Comment by sindresorhus** [comment]
Closing as this is about the command-line tool. Open a new issue on https://github.com/ImageOptim/gifski if it's still an issue.
