### ISSUE TITLE
[Feature Request] - Support for Converting PNG Sequences to GIFs 

### ISSUE THREAD

**Issue by GameChanged** [sindresorhus/Gifski#282]
Would love to see support for converting PNG Sequences to GIFs

PS - LOVE this app 👏 Amazing

**Comment by sindresorhus** [comment]
This is not something I plan to add. You could use the command-line version of Gifski instead or https://github.com/sindresorhus/Gifski#how-can-i-convert-a-sequence-of-png-images-to-a-gif
