### ISSUE TITLE
feature request: no GUI when using `Convert to GIF with Gifski` service

### ISSUE THREAD

**Issue by HazAnwar** [sindresorhus/Gifski#313]
![Screenshot 2023-08-08 at 12 16 11 pm](https://github.com/sindresorhus/Gifski/assets/3630449/d6feb259-1ae3-417f-b26e-7984bec561e0)

When using the `Convert to GIF with Gifski` service, just automatically output the GIF to the same folder without opening the GUI and having to manually press 'Save as'. 

It can just use the default GIF creation settings (or use the user's default settings but not sure if the app currently has this functionality/support). And/or just generally having an option somewhere to automatically save the GIF to the same folder (or a specified folder) rather than having to press 'Save as' every time when converting via GUI 😬

**Comment by sindresorhus** [comment]
"Services" cannot be async, so it wouldn't work.

When Gifski has a shortcut action (https://github.com/sindresorhus/Gifski/issues/246), you could make a shortcut with the setting you want and then run it without GUI from the "Quick Actions" menu.

**Comment by kornelski** [comment]
There's always the command-line https://gif.ski that you can use in scripts and automation.
