### ISSUE TITLE
Cache/Temp storage?

### ISSUE THREAD

**Issue by Laicure** [sindresorhus/Gifski#326]
Just want to ask where does it cache/save it's temporary data?
Does it magically get deleted once the app is closed (saved or unsaved)?

I just to make sure I clean it all up, thanks!

**Comment by sindresorhus** [comment]
It's written the standard temporary system directory, and macOS will clean it up once in a while. The exact location is system defined.

**Comment by Laicure** [comment]
That's great, thanks!
