### ISSUE TITLE
Update gifski library

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#51]
@kornelski Would you be able to update https://github.com/ImageOptim/gifski/tree/master/gifski.xcodeproj to latest Xcode and then update the gifski library in this repo? I noticed it has had a bunch of improvements since the last time we updated: https://github.com/ImageOptim/gifski/compare/94d6339d917b908a2eacbca6eb29599f71d8f96e...master

**Comment by sindresorhus** [comment]
I'm also seeing a bunch of warnings when compiling now:

```
:-1: object file (/Users/sindresorhus/Library/Developer/Xcode/DerivedData/Gifski-czyyuqkvdbamwdbhqpunkswgmddo/Build/Products/Debug/libgifski.a(state.o)) was built for newer OSX version (10.14) than being linked (10.13)
```

I assume we need to set the target macOS version somewhere, but not sure where.

**Comment by kornelski** [comment]
The target version is set via `MACOSX_DEPLOYMENT_TARGET` env var. I'm surprised that you see this, because Xcode generally sets it itself. Check the build log in Xcode — maybe some Xcode target has wrong deployment target set.

**Comment by kornelski** [comment]
The changes so far were cosmetic, so no rush. As I've mentioned in another thread, I want to make the C API more C-ish, so I'll have a bigger update "soon"

**Comment by sindresorhus** [comment]
> The target version is set via MACOSX_DEPLOYMENT_TARGET env var. I'm surprised that you see this, because Xcode generally sets it itself. Check the build log in Xcode — maybe some Xcode target has wrong deployment target set.

It did indeed have the wrong deploy target, but even after fixing that (https://github.com/sindresorhus/gifski-app/commit/03543bdcd9a0026d052201727f4257f88b73b1fb), I still see the warnings.
