### ISSUE TITLE
Generate GIF without asking for location

### ISSUE THREAD

**Issue by chriscalo** [sindresorhus/Gifski#72]
# Proposed interaction

1. User: drag-drops a video file onto the Gifski app window
2. App: immediately generates gif in a temp (cache) path and displays percent-complete progress
3. App: once GIF is created, a draggable preview thumbnail is displayed alongside 4 action buttons:
    - **Show in Finder**: same as today
    - **Share**: same as today
    - **Move to**: opens dialog for user to choose a destination folder and filename
    - **Copy**: copies GIF data to clipboard to paste in another app
4. User: drags preview thumbnail into another app

## What it does today
Upon drag-dropping a video file on the Gifski app, instead of starting the conversion, it immediately asks where the generated GIF should be saved.

## Preference: Always Save to Folder
For users who always want generated GIFs to be stored in the same folder, this could be done by adding an "Always Save to Folder" preference that defaults to the cache location

# Why?

I use GIFs not as a source-of-truth format, but rather as a ubiquitous, easy-to-share format to capture a few seconds of something I made or something I like. A throw-away format that only exists for sharing.

Examples:
- Take a screen recording of a prototype I made, gif it, and then drag-drop it into a chat window to my team.
- Take a screen recording of an interaction I really like in some app, gif it, and then drag-drop it into a Google Slides presentation.

So in that sense, they're like screenshots: likely not needed after they've been shared. Kinda like how macOS doesn't ask you where to save a screenshot/recording, it either just saves it, or asks you where to save it *after* it's been created.

## More context
[Twitter convo](https://twitter.com/sindresorhus/status/1110945126262534144?s=12)

**Comment by eonist** [comment]
Totally agree. Make all things like this ephemeral. Let's do it 💪 

- Store in the app cache
- Empty app cache on start and quit
- Add checkbox in prefs: Ephemeral mode (on/off) (IMO wording like save to folder just freaks people out)

**Comment by sindresorhus** [comment]
I really like this. Thanks for opening the issue.

---

> App: immediately generates gif in a temp (cache) path and displays percent-complete progress

We still have to let the user choose size, FPS, quality though. What I'm thinking is that we move those controls from the save panel into the main window.

We show the controls by default before conversion, but the user can optionally skip it by holding down Option key when dragging the video into Gifski.

The flow would be:

1. User: drag-drops a video file onto the Gifski app window
2. The controls (size, FPS, etc) fade into the main window, including a "Convert" button. If the user just wants the defaults, they just press the Enter key.

In the conversion completed view we then have:

- (Dragging the thumbnail)
- "Copy" button (and a "Copy" menu item, so they can also do Command+C)
- "Share" button
- "Save to Downloads" button
- "Save As..." button (I think this is more understandable to the user than "Move to")

I don't really see the usefulness of "Show in Finder".

Thoughts?

**Comment by mittalyashu** [comment]
What happens to the converted gif file if we click on the back button? Does it get deleted from the cache or the place where the file is temporarily stored?

**Comment by sindresorhus** [comment]
It's left in place until the OS cleans it up, usually after a few days.

**Comment by mittalyashu** [comment]
> until the OS cleans it up

Is this option by-default enable on every mac or we need to configure something in Mac settings?

**Comment by sindresorhus** [comment]
https://superuser.com/questions/187071/in-macos-how-often-is-tmp-deleted/187105
