### ISSUE TITLE
Switch from GCC to Clang

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#85]
Currently we use GCC to be able to use OpenMP, but it seems like it's actually possible to use OpenMP with the built-in Clang version in Xcode in combination with `brew install libomp`.

Resources:
- https://stackoverflow.com/a/55726616/64949
- https://stackoverflow.com/questions/44380459/is-openmp-available-in-high-sierra-llvm
- https://github.com/microsoft/LightGBM/pull/1501/files

I think it would be nicer to be able to use the built-in compiler as it means less chance of issues and probably better performance.

@kornelski Thoughts?

**Comment by kornelski** [comment]
When I have time I'll check whether libomp is usable.

However, for pngquant GCC generates better code than clang, so it wouldn't be a performance benefit.
