### ISSUE TITLE
ERROR: Unable to display save panel

### ISSUE THREAD

**Issue by kornelski** [sindresorhus/Gifski#99]
When I run e28411cfae53c7de98350069074a5fbe02a2f64e on Catalina 10.15 Beta (19A512f) after dropping a video clip I get an exception:

<details>
<summary>
<blockquote>[OpenSavePanels] ERROR: Unable to display save panel (unrecognized error: Error Domain=com.apple.ViewBridge Code=14 <br>
Invalid parameter not satisfying: aString != nil
</blockquote>
</summary>
<pre>
Gifski[70329:2386815] [OpenSavePanels] ERROR: Unable to display save panel (unrecognized error: Error Domain=com.apple.ViewBridge Code=14 "(null)" UserInfo={com.apple.ViewBridge.error.hint={
    callStackSymbols =     (
        "0   CoreFoundation                      __exceptionPreprocess + 250",
        "1   libobjc.A.dylib                     objc_exception_throw + 48",
        "2   CoreFoundation                      +[NSException raise:format:arguments:] + 88",
        "3   Foundation                          -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191",
        "4   AppKit                              -[NSMenuItem initWithTitle:action:keyEquivalent:] + 325",
        "5   AppKit                              -[NSMenu insertItemWithTitle:action:keyEquivalent:atIndex:] + 113",
        "6   FinderKit                           -[FIArrangeByMenuController configureMenu:forArrange:] + 184",
        "7   FinderKit                           -[FIArrangeByMenuController arrangeByMenu] + 130",
        "8   FinderKit                           -[FI_TArrangeByMenuController removeCommandKeyEquivalents] + 85",
        "9   FinderKit                           -[FIFinderViewGutsController prepareToShow] + 346",
        "10  FinderKit                           -[FIFinderView windowOrderedIn] + 48",
        "11  AppKit                              -[NSLocalSavePanel _navViewWindowOrderedIn] + 58",
        "12  AppKit                              -[NSLocalSavePanel _restoreDefaultSettingsForSaveMode] + 30",
        "13  AppKit                              -[NSLocalSavePanel _initPanelCommon] + 78",
        "14  AppKit                              -[NSLocalSavePanel initWithContentRect:styleMask:backing:defer:] + 703",
        "15  AppKit                              -[NSPanel init] + 75",
        "16  AppKit                              -[NSLocalSavePanel initWithOptions:] + 468",
        "17  com.apple.appkit.xpc.openAndSavePan com.apple.appkit.xpc.openAndSavePan + 11847",
        "18  com.apple.appkit.xpc.openAndSavePan com.apple.appkit.xpc.openAndSavePan + 5085",
        "19  AppKit                              -[NSViewController _loadViewIfRequired] + 72",
        "20  AppKit                              -[NSViewController view] + 23",
        "21  ViewBridge                          -[NSViewServiceMarshal _bootstrap:replyData:completion:] + 3053",
        "22  ViewBridge                          -[NSViewServiceMarshal bootstrap:withReply:] + 380",
        "23  CoreFoundation                      __invoking___ + 140",
        "24  CoreFoundation                      -[NSInvocation invoke] + 273",
        "25  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "26  ViewBridge                          -[NSVB_ViewServiceImplicitAnimationDecodingProxy forwardInvocation:] + 85",
        "27  CoreFoundation                      ___forwarding___ + 829",
        "28  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "29  CoreFoundation                      __invoking___ + 140",
        "30  CoreFoundation                      -[NSInvocation invoke] + 273",
        "31  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "32  ViewBridge                          -[NSVB_QueueingProxy forwardInvocation:] + 321",
        "33  CoreFoundation                      ___forwarding___ + 829",
        "34  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "35  CoreFoundation                      __invoking___ + 140",
        "36  CoreFoundation                      -[NSInvocation invoke] + 273",
        "37  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "38  CoreFoundation                      ___forwarding___ + 829",
        "39  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "40  CoreFoundation                      __invoking___ + 140",
        "41  CoreFoundation                      -[NSInvocation invoke] + 273",
        "42  ViewBridge                          __deferNSXPCInvocationOntoMainThread_block_invoke + 228",
        "43  ViewBridge                          __wrapBlockWithVoucher_block_invoke + 37",
        "44  ViewBridge                          __deferBlockOntoMainThread_block_invoke_2 + 507",
        "45  CoreFoundation                      __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12",
        "46  CoreFoundation                      __CFRunLoopDoBlocks + 379",
        "47  CoreFoundation                      __CFRunLoopRun + 2792",
        "48  CoreFoundation                      CFRunLoopRunSpecific + 499",
        "49  HIToolbox                           RunCurrentEventLoopInMode + 292",
        "50  HIToolbox                           ReceiveNextEventCommon + 600",
        "51  HIToolbox                           _BlockUntilNextEventMatchingListInModeWithFilter + 64",
        "52  AppKit                              _DPSNextEvent + 990",
        "53  AppKit                              -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352",
        "54  ViewBridge                          -[NSViewServiceApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 95",
        "55  AppKit                              -[NSApplication run] + 658",
        "56  AppKit                              NSApplicationMain + 777",
        "57  libxpc.dylib                        _xpc_objc_main.cold.3 + 56",
        "58  libxpc.dylib                        _xpc_objc_main + 515",
        "59  libxpc.dylib                        _xpc_copy_xpcservice_dictionary + 0",
        "60  ViewBridge                          xpc_connection_handler + 0",
        "61  ViewBridge                          NSViewServiceApplicationMain + 3071",
        "62  com.apple.appkit.xpc.openAndSavePan main + 192",
        "63  libdyld.dylib                       start + 1"
    );
    name = NSInternalInconsistencyException;
    reason = "Invalid parameter not satisfying: aString != nil";
}, com.apple.ViewBridge.error.description=NSViewBridgeServiceBootstrapError})

</pre>
</details>

and the UI doesn't open the save panel.

**Comment by kornelski** [comment]
Same for "Save As" in the remove_savepanel branch

**Comment by sunshinejr** [comment]
@kornelski yeah the open/save panel is broken on Catalina, starting beta 2. I've filled a feedback/radar but didn't get any response yet. 

Also, on current master we removed the save panel before you generate the gif so it should help a little in the meantime.

**Comment by sunshinejr** [comment]
@kornelski it is fixed in beta 5 of Catalina. Closing for now!
